# Generated by Django 4.1.13 on 2024-04-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('guest_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=100)),
                ('room_number', models.IntegerField()),
                ('room_type', models.CharField(max_length=50)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
